/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 13-Apr-2013 17:07:05
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
 #ifndef LP_FILTER_H
 #define LP_FILTER_H
 
#define LP_DBSIZE 103
#define LPSIZE 101

//#pragma DATA_SECTION(LP_Coeffs,".coeffs")
short LP_Coeffs[101] = {
        0,      0,      0,      0,      0,      0,      0,      1,      2,
        3,      4,      4,      2,     -2,     -8,    -14,    -19,    -18,
      -11,      4,     25,     46,     61,     61,     41,      0,    -57,
     -117,   -160,   -168,   -126,    -31,    105,    251,    366,    405,
      333,    138,   -158,   -500,   -800,   -956,   -875,   -494,    202,
     1162,   2280,   3404,   4366,   5014,   5243,   5014,   4366,   3404,
     2280,   1162,    202,   -494,   -875,   -956,   -800,   -500,   -158,
      138,    333,    405,    366,    251,    105,    -31,   -126,   -168,
     -160,   -117,    -57,      0,     41,     61,     61,     46,     25,
        4,    -11,    -18,    -19,    -14,     -8,     -2,      2,      4,
        4,      3,      2,      1,      0,      0,      0,      0,      0,
        0,      0
};

#endif //LP_FILTER_H
