/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 20-Apr-2013 17:43:25
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 91
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
 #define LP_DBSIZE 93
#define LPSIZE 91
short LP_Coeffs[91] = {
        0,      0,      0,      0,      1,      1,      1,      1,     -1,
       -3,     -6,     -9,     -9,     -5,      2,     14,     28,     38,
       40,     28,      0,    -41,    -87,   -123,   -132,   -102,    -26,
       88,    215,    320,    360,    301,    127,   -147,   -470,   -760,
     -918,   -848,   -482,    198,   1148,   2262,   3389,   4357,   5012,
     5243,   5012,   4357,   3389,   2262,   1148,    198,   -482,   -848,
     -918,   -760,   -470,   -147,    127,    301,    360,    320,    215,
       88,    -26,   -102,   -132,   -123,    -87,    -41,      0,     28,
       40,     38,     28,     14,      2,     -5,     -9,     -9,     -6,
       -3,     -1,      1,      1,      1,      1,      0,      0,      0,
        0
};
