/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 20-Apr-2013 17:43:25
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 91
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
 #define LP_DBSIZE 93
#define LPSIZE 91
short LP_Coeffs[91] = {
0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,
1,1,0,-1,-3,-4,-4,-3,-1,
3,7,10,11,9,4,-5,-15,-24,
-29,-26,-15,6,36,71,106,136,157,
164,157,136,106,71,36,6,-15,-26,
-29,-24,-15,-5,4,9,11,10,7,
3,-1,-3,-4,-4,-3,-1,0,1,
1,1,1,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,
0
};
