# FIXED
easi_pll.obj: ../easi_pll.c
easi_pll.obj: C:/Users/mark/Google\ Drive/EE4981H/Software/FW/EASI_ECG/include/easi_pll.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/soc.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/csl_general.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/tistdtypes.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_cpu.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_sysctrl.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_i2c.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_i2s.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_emif.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_uart.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_spi.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_mmcsd.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_lcdc.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_rtc.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_dma.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_sar.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_usb.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_gpio.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_tim.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_wdt.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_idle.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_ldo.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_mcbsp.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_mcspi.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/cslr_uhpi.h
easi_pll.obj: C:/Users/mark/Google\ Drive/EE4981H/Software/FW/EASI_ECG/include/easi_hardware.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/csl_gpio.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/csl_error.h
easi_pll.obj: C:/c55xx_csl_3.00/inc/csl_types.h
